allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
packages:
  - packages/*
overrides:
  dompurify: 3.4.12
  postcss: 8.5.23
  sharp: 0.35.4
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
minimumReleaseAgeExclude:
  - eslint@10.8.0
  - '@payloadcms/db-mongodb@3.90.1'
  - '@payloadcms/email-nodemailer@3.90.1'
  - '@payloadcms/graphql@3.90.1'
  - '@payloadcms/next@3.90.1'
  - '@payloadcms/plugin-cloud-storage@3.90.1'
  - '@payloadcms/richtext-lexical@3.90.1'
  - '@payloadcms/storage-s3@3.90.1'
  - '@payloadcms/translations@3.90.1'
  - '@payloadcms/ui@3.90.1'
  - payload@3.90.1
